### PR TITLE
feat(TemplateLibrary): add expand-collapse buttons - I80

### PR DESCRIPTION
**Pull request by tingaloo**
# Issue #80 

Builds on https://github.com/accordproject/template-studio-v2/pull/92

### Changes
- Add expand button
- Adds semantic react ui sidebar for pushable animation

### Flags
- Do we still want white hover background border? This involves being more and more custom with the sidebar.

### CODE REVIEW

**Comment by mttrbrts** [comment]
Hi @tingaloo , Can you add the DCO sign-off and rebase / merge with master, please?

**Comment by Michael-Grover** [comment]
@tingaloo I previewed the deploy at [this URL](https://5db9b36a532798000827d03b--accordproject-studio.netlify.com/) and the "hide" button looks like this:
image

Am I previewing it wrong? It looked more like this in previous iterations, right?

image

**Comment by jolanglinais** [comment]
Adding on to @Michael-Grover's comment, this looks good so far! I think addressing the `Hide` button and making it fade to the right instead of left and we're really talkin here!

**Comment by tingaloo** [comment]
One question, I thought the hide button will be placed inside ```cicero-ui``` and will take props to update the look and feel?

**Comment by jolanglinais** [comment]
@tingaloo oh right, yes. My mistake, I wasn't thinking correctly on this when I responded. Yes, I think the work will be in tandem with work in `cicero-ui`. @DianaLease thoughts?

**Comment by DianaLease** [comment]
> @tingaloo oh right, yes. My mistake, I wasn't thinking correctly on this when I responded. Yes, I think the work will be in tandem with work in `cicero-ui`. @DianaLease thoughts?

Sounds reasonable to me. We'll also want to make sure that having the button is optional, since many users of cicero-ui probably will not need this show/hide functionality.

**Comment by jolanglinais** [comment]
Closing as stale for now. Feel free to come back to it @tingaloo!

**Pull request closed without merging**
