### PR TITLE
Upgrade dependencies and style block quotes

### PR DESCRIPTION
**Pull request by DianaLease**
# Issue https://github.com/accordproject/template-studio-v2/issues/128
- chore(deps): update markdown transform and cicero-ui dependencies
- style(src): update block quote styling

Screen Shot 2019-10-25 at 4 01 48 PM

### CODE REVIEW

**Comment by jolanglinais** [comment]
Just released [`cicero-ui v0.1.7`](https://github.com/accordproject/cicero-ui/releases/tag/v0.1.7)

**Comment by Michael-Grover** [comment]
The color I chose for the line looks darker than I expected it to on a white background. Let's try this color:

image

Set the line height of the block quote text to be equal to normal text. It is currently too cramped.

The text color I chose is less legible than I hoped. Let's make it the same color as normal text. I think the vertical rule and indent should sufficiently differentiate it from normal text.

**Comment by DianaLease** [comment]
Updated based on convo IRL: Screen Shot 2019-10-25 at 5 00 11 PM

**Review by jolanglinais — APPROVED** [review]
Looks good to me.

**Pull request merged**
