### PR TITLE
A simple start to Ergo syntax highlighting

### PR DESCRIPTION
**Pull request by jeromesimeon**
Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

### CODE REVIEW

**Review by jolanglinais — DISMISSED** [review]
Looks fine to me.

**Review by DianaLease — DISMISSED** [review]
LGTM! Does it make sense to also add the `!` operator for negation?

**Comment by jeromesimeon** [comment]
> LGTM! Does it make sense to also add the `!` operator for negation?

Apparently fixing that means the review is marked as stale. I've added `!` and other missing operators. A new review please!

**Review by jolanglinais — APPROVED** [review]

**Comment by jeromesimeon** [comment]
Thanks!

**Pull request merged**
