### PR TITLE
docs(README): netlify preview badge for - 94

### PR DESCRIPTION
**Pull request by Niladri24dutta**
Signed-off-by: Niladri Dutta <nild2141@gmail.com>

## Update README

# Issue #94 

### Changes
- Added netlify preview badge for template studio V2 in README as discussed here  https://github.com/accordproject/template-studio-v2/pull/95#issuecomment-538174787

### CODE REVIEW

**Comment by Niladri24dutta** [comment]
@irmerk I have created this PR related to #94 . Can you please review it?

**Comment by jolanglinais** [comment]
@Michael-Grover thoughts on this? I think it's an improvement over just a link.

**Comment by Michael-Grover** [comment]
@irmerk This new badge is nice, but I think we should keep the traditional hyperlink in addition to it. For non developers or people not familiar with Netlify, it's very easy to not realize the badges are buttons, even if they say they go to a preview.

image

image

**Comment by jolanglinais** [comment]
@Niladri24dutta sorry, I may have overdone it by thinking this was a good change.

**Comment by Niladri24dutta** [comment]
> 
> 
> @Niladri24dutta sorry, I may have overdone it by thinking this was a good change.

@irmerk it's fine I am keeping the badge as well as the hyperlink. Will it be ok ? @Michael-Grover

**Comment by Niladri24dutta** [comment]
@Michael-Grover Can you please review it once?

**Review by Michael-Grover — APPROVED** [review]
lgtm

**Comment by Michael-Grover** [comment]
@Niladri24dutta thanks 👍

**Pull request merged**
