### PR TITLE
Update README.md for issue #94

### PR DESCRIPTION
**Pull request by Niladri24dutta**
### Changes
- add hyperlink for preview Template Studio V2 on Netlify

### CODE REVIEW

**Comment by jolanglinais** [comment]
Thanks for the PR! You'll want to add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/models/blob/master/CONTRIBUTING.md):
> Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

**Comment by Niladri24dutta** [comment]
> 
> 
> Thanks for the PR! You'll want to add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/models/blob/master/CONTRIBUTING.md):
> 
> > Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

I have provided the sign-off. Can someone review my changes and let me know if anything else is required?

**Comment by jolanglinais** [comment]
Thanks @Niladri24dutta! If you feel like it, you can open another PR to make this link into it's own badge to be next to the `netlify - success` badge that already exists.

**Review by jolanglinais — APPROVED** [review]

**Comment by Niladri24dutta** [comment]
> 
> 
> Thanks @Niladri24dutta! If you feel like it, you can open another PR to make this link into it's own badge to be next to the `netlify - success` badge that already exists.

Is there any existing markdown for the badge similar like for Netlify-success ?

**Comment by Niladri24dutta** [comment]
@irmerk also as this PR is merged can this issue #94 be closed?

**Comment by jolanglinais** [comment]
> > Thanks @Niladri24dutta! If you feel like it, you can open another PR to make this link into it's own badge to be next to the `netlify - success` badge that already exists.
> 
> Is there any existing markdown for the badge similar like for Netlify-success ?

Honestly, not sure on this one.

**Comment by Niladri24dutta** [comment]
How about this one from below ? @irmerk . Please let me know if it's fine I will create another PR and add it .
[Netlify](https://accordproject-studio.netlify.com/)

**Comment by jolanglinais** [comment]
> How about this one from below ? @irmerk . Please let me know if it's fine I will create another PR and add it .
> [Netlify](https://accordproject-studio.netlify.com/)

Yeah this looks great, open a PR and reference the same issue #94

**Pull request merged**
