### PR TITLE
fixed padding on the right sidebar

### PR DESCRIPTION
**Pull request by nik72619c**
# Issue #<NUMBER HERE>
<OVERALL SUMMARY OF PULL REQUEST>

### Changes
- Fixed padding of the template library sidebar

### Flags
- Currently the right sidebar pane did not have any padding or margin, which made it strictly squeeze with the scrollbar
ref #124

### CODE REVIEW

**Review by jolanglinais — CHANGES_REQUESTED** [review]
You'll want to add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/template-studio-v2/blob/master/CONTRIBUTING.md):
> Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

**Comment by Michael-Grover** [comment]
@nik72619c can you send a screenshot please?

**Comment by nik72619c** [comment]
shall I commit the changes again for the DCO certificate ?

**Comment by jolanglinais** [comment]
You can interactive rebase and amend the commits to have the signoff.

**Comment by Michael-Grover** [comment]
@nik72619c please send a screenshot when you have a chance and I will review, thanks

**Comment by jolanglinais** [comment]
@nik72619c any progress on this?

**Comment by jolanglinais** [comment]
Closing as stale, feel free to come back to it @nik72619c!

**Pull request closed without merging**
