### PR TITLE
refactor(src): Font Size Change From px To em - I43

### PR DESCRIPTION
**Pull request by florenciasilva**
Signed-off-by: florenciasilva <hensgrej@gmail.com>

# Issue #43 
Change in font-size to help with responsiveness. 
### Changes

- Change of all font-size from px to em. 
    * Adds initial font-size for body and #root in src/index.css 

### Flags
- Components from [@accordproject/cicero-ui](https://github.com/accordproject/cicero-ui) still contain pixels as unit for font-size.

### Related Issues
- Issue [#58](https://github.com/accordproject/cicero-ui/issues/58)

### CODE REVIEW

**Review by jolanglinais — COMMENTED** [review]
This all looks great. I'm curious why `src/containers/ContractEditor/index.js` was duplicated to `src/containers/CurrentEditor/ContractEditor/index.js`?

**Comment by florenciasilva** [comment]
> This all looks great. I'm curious why `src/containers/ContractEditor/index.js` was duplicated to `src/containers/CurrentEditor/ContractEditor/index.js`?

True! I must have miss-dragged the folder. It's fixed now!

**Review by jolanglinais — APPROVED** [review]
This looks great!

I would recommend in the future making your branch line up with the Issue (something like `florenciasilva/i43/responsive-fonts`) such as here:

Screen Shot 2019-09-25 at 9 05 07 AM

**Comment by florenciasilva** [comment]
> This looks great!
> 
> I would recommend in the future making your branch line up with the Issue (something like `florenciasilva/i43/responsive-fonts`) such as here:
> 
> Screen Shot 2019-09-25 at 9 05 07 AM

Awesome, will do next time! Thanks for all the patience!

**Pull request merged**
