### PR TITLE
feat (src): change the github ribbon for a hyperlink in top nav bar -…

### PR DESCRIPTION
**Pull request by ErnstGotera**
… 106

Signed-off-by: Emizel <Ernestogl5@hotmail.com>

# Issue #106
<OVERALL SUMMARY OF PULL REQUEST>

### Changes
- Remove Github ribbon and cdn styles
 - Add the Github hyperlink and logo

### CODE REVIEW

**Review by jolanglinais — CHANGES_REQUESTED** [review]
@Emizel you'll want to rebase with the latest master and push back up to resolve conflicts.

**Comment by jolanglinais** [comment]
Looks good so far to me, though I'd say the size for the icon and font are a bight high?

**Comment by ErnstGotera** [comment]
image
What do you think now? The font-size is the same as the others links in the navbar and I resized the logo to be 3px smaller.

**Comment by DianaLease** [comment]
Looks good to me! @irmerk & @Michael-Grover how do you feel about the size?

**Comment by Michael-Grover** [comment]
@Emizel thanks again for taking this on. These are my notes:

- The github icon looks a bit blurry and it doesn't turn green on hover. 

- I think the hover area should be a rectangle around the icon and text so that it is easier to click on. Currently if the user clicks in the small gap between the icon and text, nothing happens.

- The github icon could also be a bit smaller, see the mockup for proportions.

**Comment by ErnstGotera** [comment]
@Michael-Grover No problem, I could make the logo change color on hover and fix the blurriness if I change the png for an svg, but for that I need an npm package for loading the svg in React. Do you know any other way I could do it?

**Comment by DianaLease** [comment]
Hi @Emizel , it looks like we are already using the `file-loader` [webpack plugin](https://webpack.js.org/loaders/file-loader/) to be able to load svg files. I would see if that works for you before using another library. https://github.com/accordproject/template-studio-v2/blob/c0450097c8443c14b3458918f0c4694babb6e27c/webpack.config.js#L31

**Comment by ErnstGotera** [comment]
I added the logo svg with the file-loader and already fixed all that was asked above, but the file-loader treat the svg as an img tag so I cannot use the fill property to change the color on hover. Right now everything but that is working as requested.

**Comment by jolanglinais** [comment]
Is it not possible to use the `svg` files and manipulate them on hover? I did something similarr in the `markdown-editor` [here](https://github.com/accordproject/markdown-editor/blob/master/src/icons/bold.js) and [here](https://github.com/accordproject/markdown-editor/blob/master/src/FormattingToolbar/index.js#L186)

**Comment by ErnstGotera** [comment]
I have everything working as requested, the Github logo changes color on hovering the link, the size is reduced and the link area is increased. But I needed to install this https://www.npmjs.com/package/@svgr/webpack npm package for managing the load of the svg because the webpack file-loader treated the svg as an img thus disabling the fill property.

**Comment by Michael-Grover** [comment]
@Emizel the hover effect looks very sleek, thanks! 

The text looks a bit off-center relative to the icon. Can we move the text down 1px, without moving the icon?

**Comment by jolanglinais** [comment]
> I have everything working as requested, the Github logo changes color on hovering the link, the size is reduced and the link area is increased. But I needed to install this https://www.npmjs.com/package/@svgr/webpack npm package for managing the load of the svg because the webpack file-loader treated the svg as an img thus disabling the fill property.

I think we will wait for @DianaLease to review this.

**Comment by ErnstGotera** [comment]
Done! I moved the text 1px down

**Review by DianaLease — CHANGES_REQUESTED** [review]
This looks good, but can you remove the `.vs` directory and add it to the `gitignore` please? thanks!

**Comment by jolanglinais** [comment]
I think you should rebase to be up to date, there seem to be extra code from other commits.

**Comment by jolanglinais** [comment]
Closing as stale, referenced in #106

**Pull request closed without merging**
