### PR TITLE
fix: color contrast a11y (#133)

### PR DESCRIPTION
**Pull request by karthik1802**
# Issue #133 
<OVERALL SUMMARY OF PULL REQUEST>

### Changes
- Made changes in themeConstants.js
  - Changed color of TEMPLATE_LIBRARY['ACTION_BUTTON_BORDER'] to '#19C6C7' from '#7B8FAD.

### CODE REVIEW

**Comment by jolanglinais** [comment]
I think we'll want to decouple that border from the text color

https://deploy-preview-138--accordproject-studio.netlify.com/

**Comment by Michael-Grover** [comment]
@irmerk agreed. @akay1802 we would like the border color to remain the same as it was before.

**Comment by karthik1802** [comment]
@Michael-Grover @irmerk okay cool.. got it

**Comment by karthik1802** [comment]
I'm kinda new here so little help.. The TemplateLibrary used is imported from @accordproject/cicero-ui(which is maintained at https://github.com/accordproject/cicero-ui) so _I think_  I have to make changes there.. please tell if I'm missing something @Michael-Grover @irmerk and it's the fix I came up with https://github.com/accordproject/cicero-ui/pull/202

**Comment by jolanglinais** [comment]
@akay1802 yes! Sorry the repos are a bit confusing at first. Yes I believe that 202 PR is the fix we need. Once we merge that in, I believe this PR can be cancelled and once we make a release of `cicero-ui` and increment the version in this repo, it should be good.

**Comment by jolanglinais** [comment]
Closing for https://github.com/accordproject/cicero-ui/pull/202

**Pull request closed without merging**
