### PR TITLE
fix(TemplateLibrary): sync button colors - I135

### PR DESCRIPTION
**Pull request by aljimenez5**
# Issue #135 
<OVERALL SUMMARY OF PULL REQUEST>

### Changes
- <INSERT DESCRIPTION OF CHANGES>
  - <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>

### Flags
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>

### Related Issues
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>

### CODE REVIEW

**Comment by irmerk** [comment]
Thanks for the PR! What issue is this fixing?

**Comment by jolanglinais** [comment]
I think the issue is that the `ACTION_BUTTON_BORDER` property is tied to both the border and the `+ Add to contract` text, so they need to be decoupled.

**Comment by aljimenez5** [comment]
> I think the issue is that the `ACTION_BUTTON_BORDER` property is tied to both the border and the `+ Add to contract` text, so they need to be decoupled.

Ah gotcha - I didn't see other things change, only the button.  I have to re-look.

**Comment by jolanglinais** [comment]
Also I believe these two PRs are on this subject:

https://github.com/accordproject/template-studio-v2/pull/138
https://github.com/accordproject/cicero-ui/pull/202

**Comment by jolanglinais** [comment]
Closing as stale.

**Pull request closed without merging**
