### PR TITLE
#79: navigation: scroll to item was fixed

### PR DESCRIPTION
**Pull request by aveselovalova**
# Issue #79
scroll to items from navigation bar

### Changes
- fixed css styles
  - <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>

### Flags
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>

### Related Issues
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>

### CODE REVIEW

**Comment by jolanglinais** [comment]
Thanks for the PR! Were you able to test this and see it working? I think the issue is still persisting in the Netlify build for this PR here: https://5d9273a2b571710007bd8b7e--accordproject-studio.netlify.com/

Also, you'll want to make sure to do a couple more things to the PR as well:

- Fill out the PR more, you can reference [other merged PRs here](https://github.com/accordproject/template-studio-v2/pulls?q=is%3Apr+is%3Aclosed).
- Add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/template-studio-v2/blob/master/CONTRIBUTING.md):
> Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

**Comment by aveselovalova** [comment]
@irmerk I've tested this solution. It's scroll fine here (https://5d9273a2b571710007bd8b7e--accordproject-studio.netlify.com/)
This attach contains a demo video (chrome, mac) 
[ice_video_20191001-005512.mp4.zip](https://github.com/accordproject/template-studio-v2/files/3673603/ice_video_20191001-005512.mp4.zip)

**Comment by jolanglinais** [comment]
The toolbar is going off the screen with your Netlify deployment: https://www.loom.com/share/70d1bb2366c04366897b10bf1bf5e55b

**Comment by aveselovalova** [comment]
ok, I'll fix it

**Comment by DianaLease** [comment]
This issue was fixed in https://github.com/accordproject/template-studio-v2/pull/104, so I will close this PR.

**Pull request closed without merging**
