### PR TITLE
feat(Error): convert array of errors to object with indexed errors - I86

### PR DESCRIPTION
**Pull request by Ph0tonic**
# Issue #86 
Right now, the errors get added to an array every time a clause is parsed. This means if multiple changes cause a clause to be parsed multiple times, the same error will be added to the array multiple times and we end up with multiple of the same error.

### Changes
- Convert array of errors to an object with indexed errors

### Flags
- Needs update in cicero-ui for errors management, see related issue

### Related Issues
- Issue #86 
- accordproject/cicero-ui#137

### CODE REVIEW

**Review by adriaan-pelzer — DISMISSED** [review]
I had a chat with @irmerk to understand what is needed here, and as far as I can see, this looks spot on.

**Comment by DianaLease** [comment]
awesome! Let's make sure we get the corresponding [issue](https://github.com/accordproject/cicero-ui/issues/137) in cicero-ui resolved as well so the ErrorLogger can handle this new object. Great job!

**Comment by DianaLease** [comment]
Hi @Ph0tonic! I wanted to let you know that @flagoon is working on the corresponding issue in cicero-ui here: https://github.com/accordproject/cicero-ui/issues/137, so it might make sense to connect with them and see if you can test the two out together! 😃

**Review by jolanglinais — APPROVED** [review]
This looks good to me. Great changes! I'm going to merge this in and we can iron out any possible bugs through [Cicero-UI #167](https://github.com/accordproject/cicero-ui/issues/167)

**Review by jolanglinais — CHANGES_REQUESTED** [review]
Actually, would you update `cicero-ui` in the `package.json` to `v0.1.3`?

**Comment by Ph0tonic** [comment]
Yes of course, here it's.

**Review by jolanglinais — APPROVED** [review]

**Pull request merged**
