### PR TITLE
feat(TemplateLibrary): add expand-collapse buttons - I80

### PR DESCRIPTION
**Pull request by tingaloo**
# Issue #80 

Bumps the issue to add collapse and expand buttons. It follows the look and behavior of the mockups. Currently implemented for one side only before fixing the other side.

### Changes
- Add expand button
- Add collapse button
  -  It only shows on hovering over the sidebar with a faint border.

### Flags
- Waiting to see if this is the look and feel before working on the left sidebar.

### TODO

- [ ] Add logic to left sidebar
- [ ] Write react hook tests?

Screen Shot 2019-10-02 at 00 06 16
Screen Shot 2019-10-02 at 00 03 03

### CODE REVIEW

**Comment by jolanglinais** [comment]
@DianaLease and @michael-grover, preview can be seen here: https://5d9424a22f35820008ddf645--accordproject-studio.netlify.com/

**Comment by jolanglinais** [comment]
@tingaloo I think this is in the right direction! I would use the mockups in the issue to get it closer to spec. You could definitely keep it to the right navbar for now, and once that's good, we can merge that in and you continue on to the left if you want.

**Comment by Michael-Grover** [comment]
@tingaloo please let me know if you have any questions about the mockups in issue #80 . Here is some broad feedback, though it doesn't cover everything:

The "expand" button should be on the outer edge of the screen when the pane is collapsed.

image


The expand button in this PR does not match the appearance of the mockup
image

The color of the button should appear different depending on whether the user is hovering over it or not:
image
image

**Comment by tingaloo** [comment]
Sounds good, the icons are beyond semantic UI react icons. I'll write them
out tonight.

Also the contribute to github banner covers the expand icon in the current
dev build. But I'll flush it to the right for the final build.

**Comment by Michael-Grover** [comment]
@irmerk @DianaLease can we get rid of the github banner or move it somewhere else?

@tingaloo would you prefer if I sent you SVGs or PNGs of the icons?

**Comment by tingaloo** [comment]
Svgs of the icons would make things easier, otherwise I would need to play with the css stylings and make it look like so.

```const CollapseIcon = styled(Icon)`
  cursor:pointer;
  height:2rem;
  width:2rem;
  top:2em;
  left:-.5em;
  z-index:999;
  color:white;
  position: absolute;
  display: inline-block;
  border:solid;
  border-radius: 60px;
  background-color:#1ac7c7;
border-width:1px;
color:white;
`;```

However if the svgs are already there, that would be nice!

**Comment by Michael-Grover** [comment]
@tingaloo I should be able to send these SVGs later today, sorry for the delay.

**Comment by Michael-Grover** [comment]
Hi @tingaloo , here are the files I promised. Let me know if you need anything else

green menu

white menu

green arrow

white arrow

[svg files.zip](https://github.com/accordproject/template-studio-v2/files/3683208/svg.files.zip)

**Comment by tingaloo** [comment]
Screen Shot 2019-10-02 at 19 16 35
Screen Shot 2019-10-02 at 19 16 39

Getting there!

**Comment by tingaloo** [comment]
keeping the expand button ```justified start``` until we have movement on the contribute to github ribbon.

**Comment by jolanglinais** [comment]
> keeping the expand button `justified start` until we have movement on the contribute to github ribbon.

I believe the contribute ribbon will be there permanently. It was in the first issue of `template-studio`, at least. @jeromesimeon and @dselman thoughts?

**Comment by Michael-Grover** [comment]
@irmerk @tingaloo do you know where I can see a Netlify preview of this like this preview there was for the first draft? 

https://5d9424a22f35820008ddf645--accordproject-studio.netlify.com/

**Comment by Michael-Grover** [comment]
https://5d9686358a64ab0008186999--accordproject-studio.netlify.com/

@tingaloo 
I don't see the expand button in this Netlify preview. Maybe I'm previewing this wrong?

For the ribbon issue, what if we put the expand button below the ribbon for now?
image

**Comment by tingaloo** [comment]
I moved it below the ribbon!

**Comment by jolanglinais** [comment]
I think since no one has chimed in, let's just get rid of the banner.

This is looking great @tingaloo, really appreciate all this contribution! I feel like we're nearly there for the right side.

I have a few notes:
- The arrow in the collapse button is a bit off center.
- The hamburger icon does not change color on hover.
  - It's also possibly slightly smaller than the arrow button?
- I think there should be a way to have the arrow icon appear without creating a `1px` div which then offsets the rest of the component. Maybe trying a [React.Fragment](https://reactjs.org/docs/fragments.html)?

**Comment by Michael-Grover** [comment]
@tingaloo sorry for not chiming in for a bit. @irmerk thanks for responding during the weekend. I second your feedback.

**Comment by tingaloo** [comment]
Fixed the hamburger button to use an image to be consistent with the collapse arrow.

Also I made the border-left stretch the entire component, however that makes it also hoverable during the expanded state. Currently using CSS to manage hover state but i can make it a javascript state if we want to disable the border-left hover on expand hamburger icon.

Also arrow is centered based on CSS dimensions, but i can add additional padding to it.

**Comment by jolanglinais** [comment]
I'll be able to review further tomorrow, but I think the main thing left is just that `1px` white line/border that appears when hovering over the template library.

**Comment by Michael-Grover** [comment]
The lack of padding on the left side and the always present dark scroll bar make it difficult to review the border that appears at the left. I think those are different issues unrelated to the menu and can be addressed separately.

image

Removing the "Hide Clause Templates" text button has resulted in there being no margin/padding above the topmost text elements of this component. Let's add padding back in so it looks more like the mockup
Then:
image
Now:
image

Mockup:
image

Can we move the arrow icon to be between the Clause Templates headline and the search bar such that it doesn't obscure the search bar? Can this be done in a way so that the location of the button adapts to the content of the component? So that for example, if we add the "New clause template" button in the future, the arrow icon will automatically adjust to not overlap it, but still be horizontally centered on the vertical line?

See mockup and your first PR
image
image

**Comment by tingaloo** [comment]
To get the arrow be positioned relatively, i need to position relative to the searchbar or text, which reside in the ```<TemplateLibrary/>``` component.

That would let the presentation logic leak into the core library and create a dependency between the two. I'm not sure that's what we want to do, perhaps the collapse button can be positioned in the center similar to VSC's (or similar IDE) sidebar?

**Comment by jolanglinais** [comment]
@tingaloo I think that having the arrow/burger buttons in the `TemplateLibrary`, and accept a callback from above to perform the action, could be a good path forward. @DianaLease thoughts?

**Comment by DianaLease** [comment]
> @tingaloo I think that having the arrow/burger buttons in the `TemplateLibrary`, and accept a callback from above to perform the action, could be a good path forward. @DianaLease thoughts?

Do you mean the `TemplateLibrary` component in cicero-ui or the container in template-studio-v2? If we move this into cicero-ui, we would want a way to be able to change the colors of these arrow/burger icons using props, since other parties importing `TemplateLibrary` from cicero-ui may not want them to be teal. (@tingaloo cicero-ui is a library of components meant to be able to be imported by other apps, as it is here in template-studio-v2).

**Comment by jolanglinais** [comment]
Precisely. This will be similar to the `TemplateLibrary` itself, which is styled through optional props (and defaults to our AP style).

**Comment by jolanglinais** [comment]
@tingaloo what is the status of this at the moment?

**Comment by tingaloo** [comment]
@irmerk Based on the above conversation, we want a default collapse button in the ```<TemplateLibrary/>``` component in ```cicero-ui``` which accepts a prop that styles the button color AND accepts a toggleCollapse prop?

This requires another PR in cicero-ui if that were the case.

**Comment by jolanglinais** [comment]
@tingaloo I believe so. I suspect the best course of action is to close this PR and adapt the work you've done in it to both `template-studio-v2` and `cicero-ui`, and open a pair of PRs at the same time.

**Comment by tingaloo** [comment]
Linking https://github.com/accordproject/cicero-ui/pull/170

**Comment by jolanglinais** [comment]
Conversation on Slack: https://accord-project.slack.com/archives/C7U521CTG/p1571750716034700

**Comment by jolanglinais** [comment]
@tingaloo apologies for the delays. I think the best course of action based from that Slack discussion is to pass collapsing functionality down to `cicero-ui` to use in a button. And this repo will wrap `TemplateLibrary` in a "pushable" [Semantic UI React Sidebar](https://semantic-ui.com/modules/sidebar.html#/examples) which will then collapse and expand.

Does that all make sense?

**Comment by tingaloo** [comment]
@irmerk So everything is the same aesthetic wise.

Only difference is template studio imports semantic ui react sidebar to wrap? And ```TemplateLibrary``` accepts the toggleCollapse?

**Comment by jolanglinais** [comment]
> Only difference is template studio imports semantic ui react sidebar to wrap? And `TemplateLibrary` accepts the toggleCollapse?

I believe so, yes.

**Comment by Michael-Grover** [comment]
Does this affect how the UI will look?

**Comment by jolanglinais** [comment]
> Does this affect how the UI will look?

I think that will be more clear as @tingaloo works on it more.

**Comment by tingaloo** [comment]
Screen Shot 2019-10-24 at 10 17 08 AM


Wrapping the <TemplateLibrary/ > with sidebar looks like so, is that good?

**Comment by jolanglinais** [comment]
@tingaloo no, that doesn't. Semantic UI React is frustrating. Are we not able to overwrite the background color and remove that border?

**Comment by tingaloo** [comment]
We can! I will try and get the pushable features out later today.

**Pull request closed without merging**
