### PR TITLE
style(templatelibrary): fix padding in template library sidebar - I124

### PR DESCRIPTION
**Pull request by sachdeva-shrey**
Signed-off-by: Shrey Sachdeva <shreysachdeva.2000@gmail.com>

# Issue #124 
- Fixed padding of the template library sidebar

### Changes
- Added left-margin(15px)
- Changed right-margin(15px)

### Flags
- N/A

### CODE REVIEW

**Comment by sachdeva-shrey** [comment]
**Changes can be seen here in this screenshot:** 

margin

**Comment by sachdeva-shrey** [comment]
Does this look okay? @Michael-Grover @irmerk

**Review by Michael-Grover — APPROVED** [review]
lgtm, thank you

**Review by elit-altum — APPROVED** [review]
lgtm

**Pull request merged**
